package Playground.editing;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class SomeDiagram extends JFrame {
  private JPanel panel = new JPanel() {
    @Override
    protected void paintComponent(Graphics graphics) {
      super.paintComponent(graphics);
      graphics.setColor(Color.RED);
      graphics.drawOval(4, 10, 50, 50);
      graphics.setColor(Color.BLUE);
      graphics.drawRect(49, 19, 49, 49);
    }
  };


  private void initialize() {
    this.setTitle("SomeDiagram");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }



  public static void main(String[] args) {
    SomeDiagram canvas = new SomeDiagram();
    canvas.initialize();
  }
}
