package org.campagnelab.mps.editor2svg.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum RenderingOutputFormat {
  SVG("SVG", 0),
  PDF("PDF", 1);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<RenderingOutputFormat> getConstants() {
    List<RenderingOutputFormat> list = ListSequence.fromList(new LinkedList<RenderingOutputFormat>());
    ListSequence.fromList(list).addElement(RenderingOutputFormat.SVG);
    ListSequence.fromList(list).addElement(RenderingOutputFormat.PDF);
    return list;
  }

  public static RenderingOutputFormat getDefault() {
    return RenderingOutputFormat.PDF;
  }

  public static RenderingOutputFormat parseValue(String value) {
    if (value == null) {
      return RenderingOutputFormat.getDefault();
    }
    if (value.equals(RenderingOutputFormat.SVG.getValueAsString())) {
      return RenderingOutputFormat.SVG;
    }
    if (value.equals(RenderingOutputFormat.PDF.getValueAsString())) {
      return RenderingOutputFormat.PDF;
    }
    return RenderingOutputFormat.getDefault();
  }

  private int myValue;

  RenderingOutputFormat(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
