package org.campagnelab.mps.editor2svg.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

@Generated
public class QueriesGenerated {
  public static SNode sourceNodeQuery_8751972264247981389(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    // wrap the input node in the tee editor component 
    return _context.getNode();
  }
}
