package org.campagnelab.mps.editor2pdf.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.intentions.IntentionsManager;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("93bc01ac-08ca-4f11-9c7d-614d04055dfb(org.campagnelab.mps.editor2pdf)"), PersistenceFacade.getInstance().createModelReference("r:6bb9f222-b46c-45b3-85b5-99e8faaeadce(org.campagnelab.mps.editor2pdf.intentions)"));
  }

  public void init() {
    IntentionsManager.getInstance().registerIntentionFactory(new RefreshRenderings_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new Render_Intention());
    IntentionsManager.getInstance().registerIntentionFactory(new TogglePDFRendering_Intention());
  }
}
