package org.campagnelab.refexample.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_NavigateToNode = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_RefTarget = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_WithRef = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.NavigateToNode:
        return props_NavigateToNode;
      case LanguageConceptSwitch.RefTarget:
        return props_RefTarget;
      case LanguageConceptSwitch.WithRef:
        return props_WithRef;
    }
    return null;
  }
}
