package org.campagnelab.refexample.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int NavigateToNode = 0;
  public static final int RefTarget = 1;
  public static final int WithRef = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x85d7c0cc4aa84799L, 0x8fbab6f80d065fa5L);
    builder.put(0x386faece7275f748L, NavigateToNode);
    builder.put(0x386faece7275f6beL, RefTarget);
    builder.put(0x386faece7275f6bbL, WithRef);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
