package org.campagnelab.mps.editor2pdf.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int DefaultOutputDirectory = 0;
  public static final int DiagramOutputDirectory = 1;
  public static final int DiagramRef = 2;
  public static final int EditorAnnotation = 3;
  public static final int Font = 4;
  public static final int PdfCollection = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL);
    builder.put(0xc65f8233c995462L, DefaultOutputDirectory);
    builder.put(0xc65f8233c993928L, DiagramOutputDirectory);
    builder.put(0xc65f8233c9b5596L, DiagramRef);
    builder.put(0x79754067868533ecL, EditorAnnotation);
    builder.put(0x2b38d40c9f277222L, Font);
    builder.put(0xc65f8233c9b555cL, PdfCollection);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
