package org.campagnelab.mps.editor2pdf.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptDefaultOutputDirectory = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DefaultOutputDirectory", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c995462L)).super_("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory").super_(MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L)).parents("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory").parentIds(MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L)).create();
  /*package*/ final ConceptDescriptor myConceptDiagramOutputDirectory = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(893392931327129956L, "path")).properties("path").alias("Output", "Output directory for SVG Renderings").create();
  /*package*/ final ConceptDescriptor myConceptDiagramRef = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DiagramRef", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b5596L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(893392931327268247L, "diagram", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x79754067868533ecL), false)).references("diagram").create();
  /*package*/ final ConceptDescriptor myConceptEditorAnnotation = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.EditorAnnotation", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x79754067868533ecL)).super_("jetbrains.mps.lang.core.structure.NodeAttribute").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L)).parents("jetbrains.mps.lang.core.structure.NodeAttribute", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5378718574870043633L, "outputFormat")).properties("outputFormat").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8751972264247713726L, "editor", MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10f7df344a9L), true), new ConceptDescriptorBuilder.Ref(893392931327136863L, "outputTo", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L), true)).references("editor", "outputTo").create();
  /*package*/ final ConceptDescriptor myConceptPdfCollection = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.PdfCollection", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b555cL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(893392931327268244L, "diagrams", MetaIdFactory.conceptId(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b5596L), true, true, false)).children(new String[]{"diagrams"}, new boolean[]{true}).alias("pdf-collection", "Collection of PDF editor annotations").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDefaultOutputDirectory, myConceptDiagramOutputDirectory, myConceptDiagramRef, myConceptEditorAnnotation, myConceptPdfCollection);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0j, conceptFqName)) {
      case 0:
        return myConceptDefaultOutputDirectory;
      case 1:
        return myConceptDiagramOutputDirectory;
      case 2:
        return myConceptDiagramRef;
      case 3:
        return myConceptEditorAnnotation;
      case 4:
        return myConceptPdfCollection;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0j = new String[]{"org.campagnelab.mps.editor2pdf.structure.DefaultOutputDirectory", "org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory", "org.campagnelab.mps.editor2pdf.structure.DiagramRef", "org.campagnelab.mps.editor2pdf.structure.EditorAnnotation", "org.campagnelab.mps.editor2pdf.structure.PdfCollection"};
}
