package org.campagnelab.mps.editor2pdf.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.UUID;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptDefaultOutputDirectory = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DefaultOutputDirectory", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327136866L)).super_("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory").super_(MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327129896L)).parents("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory").parentIds(MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327129896L)).create();
  /*package*/ final ConceptDescriptor myConceptDiagramOutputDirectory = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327129896L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(893392931327129956L, "path")).properties("path").alias("Output", "Output directory for SVG Renderings").create();
  /*package*/ final ConceptDescriptor myConceptDiagramRef = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.DiagramRef", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327268246L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(893392931327268247L, "diagram", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 8751972264247112684L), false)).references("diagram").create();
  /*package*/ final ConceptDescriptor myConceptEditorAnnotation = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.EditorAnnotation", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 8751972264247112684L)).super_("jetbrains.mps.lang.core.structure.NodeAttribute").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 3364660638048049748L)).parents("jetbrains.mps.lang.core.structure.NodeAttribute", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 3364660638048049748L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5378718574870043633L, "outputFormat")).properties("outputFormat").referenceDescriptors(new ConceptDescriptorBuilder.Ref(8751972264247713726L, "editor", MetaIdFactory.conceptId(UUID.fromString("18bc6592-03a6-4e29-a83a-7ff23bde13ba"), 1166049232041L), true), new ConceptDescriptorBuilder.Ref(893392931327136863L, "outputTo", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327129896L), true)).references("editor", "outputTo").create();
  /*package*/ final ConceptDescriptor myConceptPdfCollection = new ConceptDescriptorBuilder("org.campagnelab.mps.editor2pdf.structure.PdfCollection", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327268188L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1133920641626L), MetaIdFactory.conceptId(UUID.fromString("ceab5195-25ea-4f22-9b92-103b95ca8c0c"), 1169194658468L)).childDescriptors(new ConceptDescriptorBuilder.Link(893392931327268244L, "diagrams", MetaIdFactory.conceptId(UUID.fromString("93bc01ac-08ca-4f11-9c7d-614d04055dfb"), 893392931327268246L), true, true, false)).children(new String[]{"diagrams"}, new boolean[]{true}).alias("pdf-collection", "Collection of PDF editor annotations").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDefaultOutputDirectory, myConceptDiagramOutputDirectory, myConceptDiagramRef, myConceptEditorAnnotation, myConceptPdfCollection);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0j, conceptFqName)) {
      case 0:
        return myConceptDefaultOutputDirectory;
      case 1:
        return myConceptDiagramOutputDirectory;
      case 2:
        return myConceptDiagramRef;
      case 3:
        return myConceptEditorAnnotation;
      case 4:
        return myConceptPdfCollection;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0j = new String[]{"org.campagnelab.mps.editor2pdf.structure.DefaultOutputDirectory", "org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory", "org.campagnelab.mps.editor2pdf.structure.DiagramRef", "org.campagnelab.mps.editor2pdf.structure.EditorAnnotation", "org.campagnelab.mps.editor2pdf.structure.PdfCollection"};
}
