package org.campagnelab.mps.editor2pdf.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptDefaultOutputDirectory = createDescriptorForDefaultOutputDirectory();
  /*package*/ final ConceptDescriptor myConceptDiagramOutputDirectory = createDescriptorForDiagramOutputDirectory();
  /*package*/ final ConceptDescriptor myConceptDiagramRef = createDescriptorForDiagramRef();
  /*package*/ final ConceptDescriptor myConceptEditorAnnotation = createDescriptorForEditorAnnotation();
  /*package*/ final ConceptDescriptor myConceptFont = createDescriptorForFont();
  /*package*/ final ConceptDescriptor myConceptPdfCollection = createDescriptorForPdfCollection();
  private final LanguageConceptSwitch myConceptIndex;

  public StructureAspectDescriptor() {
    myConceptIndex = new LanguageConceptSwitch();
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDefaultOutputDirectory, myConceptDiagramOutputDirectory, myConceptDiagramRef, myConceptEditorAnnotation, myConceptFont, myConceptPdfCollection);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myConceptIndex.index(id)) {
      case LanguageConceptSwitch.DefaultOutputDirectory:
        return myConceptDefaultOutputDirectory;
      case LanguageConceptSwitch.DiagramOutputDirectory:
        return myConceptDiagramOutputDirectory;
      case LanguageConceptSwitch.DiagramRef:
        return myConceptDiagramRef;
      case LanguageConceptSwitch.EditorAnnotation:
        return myConceptEditorAnnotation;
      case LanguageConceptSwitch.Font:
        return myConceptFont;
      case LanguageConceptSwitch.PdfCollection:
        return myConceptPdfCollection;
      default:
        return null;
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myConceptIndex.index(c);
  }

  private static ConceptDescriptor createDescriptorForDefaultOutputDirectory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "DefaultOutputDirectory", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c995462L);
    b.class_(false, false, false);
    b.super_("org.campagnelab.mps.editor2pdf.structure.DiagramOutputDirectory", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/893392931327136866");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagramOutputDirectory() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "DiagramOutputDirectory", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/893392931327129896");
    b.prop("path", 0xc65f8233c993964L, "893392931327129956");
    b.aggregate("font", 0x2b38d40c9f277226L).target(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x2b38d40c9f277222L).optional(true).ordered(true).multiple(false).origin("3114472293001556518").done();
    b.alias("Output");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDiagramRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "DiagramRef", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b5596L);
    b.class_(false, false, false);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/893392931327268246");
    b.associate("diagram", 0xc65f8233c9b5597L).target(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x79754067868533ecL).optional(false).origin("893392931327268247").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForEditorAnnotation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "EditorAnnotation", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x79754067868533ecL);
    b.class_(false, false, false);
    b.super_("jetbrains.mps.lang.core.structure.NodeAttribute", 0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/8751972264247112684");
    b.prop("outputFormat", 0x4aa50c0bd1ec9bf1L, "5378718574870043633");
    b.associate("editor", 0x79754067868e5fbeL).target(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10f7df344a9L).optional(true).origin("8751972264247713726").done();
    b.associate("outputTo", 0xc65f8233c99545fL).target(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c993928L).optional(true).origin("893392931327136863").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFont() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "Font", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0x2b38d40c9f277222L);
    b.class_(false, false, false);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/3114472293001556514");
    b.prop("filename", 0x2b38d40c9f277223L, "3114472293001556515");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPdfCollection() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("org.campagnelab.mps.editor2pdf", "PdfCollection", 0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b555cL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:7a57a805-2fc1-49f5-991a-6bd531b99008(org.campagnelab.mps.editor2pdf.structure)/893392931327268188");
    b.aggregate("diagrams", 0xc65f8233c9b5594L).target(0x93bc01ac08ca4f11L, 0x9c7d614d04055dfbL, 0xc65f8233c9b5596L).optional(true).ordered(true).multiple(true).origin("893392931327268244").done();
    b.alias("pdf-collection");
    return b.create();
  }
}
