package org.campagnelab.mps.editor2pdf.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class DefaultOutputDirectory_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "path", "./");
    SPropertyOperations.set(thisNode, "name", "default");
  }
}
