package org.campagnelab.mps.editor2pdf.behavior;

/*Generated by MPS */


public interface SVGWriter {
  void write(String svgFragment);
  void append(String svgFragment);
  String toString();
  void close();
}
