package org.campagnelab.mps.editor2svg.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import org.apache.batik.dom.util.DOMUtilities;
import org.apache.batik.dom.svg.SVGDOMImplementation;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.apache.batik.svggen.SVGGraphics2D;
import jetbrains.mps.nodeEditor.cells.ParentSettings;
import java.io.StringWriter;
import java.io.Writer;
import java.io.PrintWriter;
import java.io.File;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.apache.log4j.Priority;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class EditorAnnotation_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "outputTo", SConceptOperations.createNewNode("org.campagnelab.mps.editor2svg.structure.DefaultOutputDirectory", null), false);
  }

  public static void call_renderNodeEditor_8751972264248786149(SNode thisNode, SNode annotation, EditorCell editorCell) {
    // jetbrains.mps.nodeEditor.cells.EditorCell 

    /*
      editorCell.synchronizeViewWithModel();
    */

    DOMUtilities domUtil;
    try {
      String svgNS = SVGDOMImplementation.SVG_NAMESPACE_URI;
      DOMImplementation impl = SVGDOMImplementation.getDOMImplementation();
      Document doc1 = impl.createDocument(svgNS, "svg", null);

      Document doc = impl.createDocument(svgNS, "svg", null);


      SVGGraphics2D graphics = new SVGGraphics2D(doc);
      ParentSettings settings = new ParentSettings();

      editorCell.paint(graphics, settings);
      editorCell.relayout();

      StringWriter sw = new StringWriter();
      Writer writer = new PrintWriter(new File("/data/" + SPropertyOperations.getString(annotation, "name") + ".svg"));
      graphics.stream(writer, false);
      writer.close();
    } catch (Exception e) {
      if (LOG.isEnabledFor(Priority.ERROR)) {
        LOG.error("Exception", e);
      }
      e.printStackTrace();
    }

  }

  protected static Logger LOG = LogManager.getLogger(EditorAnnotation_Behavior.class);
}
